// This file is a placeholder for auto-generated component types by unplugin-vue-components.
// After running `npm install` and `npm run dev` or `npm run build`,
// this file should be automatically populated with types for Element Plus components
// and any other globally registered components.
// Example (auto-generated content):
//
// // generated by unplugin-vue-components
// // We suggest you to commit this file into source control
// // Read more: https://github.com/vuejs/core/pull/3399
// import '@vue/runtime-core'
//
// export {}
//
// declare module '@vue/runtime-core' {
//   export interface GlobalComponents {
//     // Element Plus components will be listed here, e.g.:
//     // ElButton: typeof import('element-plus/es')['ElButton']
//     // ElInput: typeof import('element-plus/es')['ElInput']
//     RouterLink: typeof import('vue-router')['RouterLink']
//     RouterView: typeof import('vue-router')['RouterView']
//   }
// }
